# Generated by Django 5.1.7 on 2025-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                blank=True,
                choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                max_length=10,
            ),
        ),
    ]
