# Generated by Django 5.1.7 on 2025-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_tracker", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
