# Generated by Django 5.1.7 on 2025-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_tracker", "0003_alter_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
